version: "3.3"

services:
  drugbank-db:
    image: postgres:13.1
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: drugbank
      POSTGRES_PASSWORD: drugbank
      POSTGRES_DB: drugbank
      POSTGRES_HOST: db
    ports:
      - 5433:5432
    networks:
      - drugbank
  drugbank-db-mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
#  sqlitebrowser:
#    image: lscr.io/linuxserver/sqlitebrowser:latest
#    container_name: sqlitebrowser
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/London
#    volumes:
#      - sqlite-data:/config
#      - ./disgenet_2020.db:/config/disgenet_2020.db.db
#    ports:
#      - 3000:3000
#    restart: unless-stopped
volumes:
  postgres-data:
  mongo-data:
  sqlite-data:
networks:
  drugbank: